<a href="https://colab.research.google.com/github/FariyalShaik/Credit_Card_Fraud_Detection_Project/blob/main/credit_card_fraud_detection1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
#loading the dataset to a pandas dataframe
credit_card_data=pd.read_csv("/content/creditcard[1].csv")
credit_card_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,1524,-0.340622,1.132232,1.291494,0.062313,0.016387,-0.977070,0.723755,-0.074630,-0.396655,...,-0.262948,-0.688785,-0.010937,0.334061,-0.160025,0.071779,0.245128,0.098336,5.35,0.0
1982,1525,-1.842696,1.740641,0.861526,-0.856315,-0.655376,-0.842786,0.198563,0.602764,0.455595,...,-0.213609,-0.400617,0.030013,0.512611,-0.077087,0.286218,0.586012,0.352610,1.00,0.0
1983,1525,-0.480693,0.646091,1.577264,-0.084411,-0.305958,-0.534739,0.860346,-0.028569,-0.800705,...,0.121681,0.175190,0.035986,0.557665,-0.112301,0.337154,-0.015602,0.051504,80.70,0.0
1984,1525,-0.342132,1.091125,1.282729,0.068076,-0.022498,-0.996727,0.676304,-0.042250,-0.312036,...,-0.269850,-0.734148,-0.007354,0.319161,-0.179146,0.073683,0.241932,0.097139,3.59,0.0
1985,1526,-0.854343,1.382948,1.278665,2.914727,-0.183139,-0.349329,0.274566,0.435277,-1.576521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
#last 5 rows of the dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1981,1524,-0.340622,1.132232,1.291494,0.062313,0.016387,-0.977070,0.723755,-0.074630,-0.396655,...,-0.262948,-0.688785,-0.010937,0.334061,-0.160025,0.071779,0.245128,0.098336,5.35,0.0
1982,1525,-1.842696,1.740641,0.861526,-0.856315,-0.655376,-0.842786,0.198563,0.602764,0.455595,...,-0.213609,-0.400617,0.030013,0.512611,-0.077087,0.286218,0.586012,0.352610,1.00,0.0
1983,1525,-0.480693,0.646091,1.577264,-0.084411,-0.305958,-0.534739,0.860346,-0.028569,-0.800705,...,0.121681,0.175190,0.035986,0.557665,-0.112301,0.337154,-0.015602,0.051504,80.70,0.0
1984,1525,-0.342132,1.091125,1.282729,0.068076,-0.022498,-0.996727,0.676304,-0.042250,-0.312036,...,-0.269850,-0.734148,-0.007354,0.319161,-0.179146,0.073683,0.241932,0.097139,3.59,0.0
1985,1526,-0.854343,1.382948,1.278665,2.914727,-0.183139,-0.349329,0.274566,0.435277,-1.576521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
credit_card_data.shape

(1986, 31)

In [6]:
#dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1986 entries, 0 to 1985
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    1986 non-null   int64
 1   V1      1986 non-null   float64
 2   V2      1986 non-null   float64
 3   V3      1986 non-null   float64
 4   V4      1986 non-null   float64
 5   V5      1986 non-null   float64
 6   V6      1986 non-null   float64
 7   V7      1986 non-null   float64
 8   V8      1986 non-null   float64
 9   V9      1986 non-null   float64
 10  V10     1986 non-null   float64
 11  V11     1986 non-null   float64
 12  V12     1986 non-null   float64
 13  V13     1986 non-null   float64
 14  V14     1985 non-null   float64
 15  V15     1985 non-null   float64
 16  V16     1985 non-null   float64
 17  V17     1985 non-null   float64
 18  V18     1985 non-null   float64
 19  V19     1985 non-null   float64
 20  V20     1985 non-null   float64
 21  V21     1985 non-null   float64
 22  V22     1985 non-null   float64
 23  V23     1985 non-null   float64
 24  V24     1985 non-null   float64
 25  V25     1985 non-null   float64
 26  V26     1985 non-null   float64
 27  V27     1985 non-null   float64
 28  V28     1985 non-null   float64
 29  Amount  1985 non-null   float64
 30  Class   1985 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 481.1 KB

In [7]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

methods to solve the missing values

imputation

dropping(for large data)

In [8]:
new_credit_card_data=credit_card_data.dropna(how='any')
new_credit_card_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1980,1524,-1.278672,1.318588,1.321637,-0.842274,-0.323036,-0.753479,0.595773,0.160145,0.431263,...,-0.228278,-0.365055,-0.023650,0.517183,-0.149327,0.279858,0.608979,0.353802,5.00,0.0
1981,1524,-0.340622,1.132232,1.291494,0.062313,0.016387,-0.977070,0.723755,-0.074630,-0.396655,...,-0.262948,-0.688785,-0.010937,0.334061,-0.160025,0.071779,0.245128,0.098336,5.35,0.0
1982,1525,-1.842696,1.740641,0.861526,-0.856315,-0.655376,-0.842786,0.198563,0.602764,0.455595,...,-0.213609,-0.400617,0.030013,0.512611,-0.077087,0.286218,0.586012,0.352610,1.00,0.0
1983,1525,-0.480693,0.646091,1.577264,-0.084411,-0.305958,-0.534739,0.860346,-0.028569,-0.800705,...,0.121681,0.175190,0.035986,0.557665,-0.112301,0.337154,-0.015602,0.051504,80.70,0.0
1984,1525,-0.342132,1.091125,1.282729,0.068076,-0.022498,-0.996727,0.676304,-0.042250,-0.312036,...,-0.269850,-0.734148,-0.007354,0.319161,-0.179146,0.073683,0.241932,0.097139,3.59,0.0

In [9]:
new_credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [10]:
new_credit_card_data.shape

(1985, 31)

In [11]:
#distribution of legit transaction & fraudulent tansaction
new_credit_card_data['Class'].value_counts()

0.0    1983
1.0       2
Name: Class, dtype: int64

this dataset is highly unbalanced

0-->normal transaction

1-->fraudulent transaction

In [12]:
# separating data for analysis
legit=new_credit_card_data[new_credit_card_data.Class==0]
fraud=new_credit_card_data[new_credit_card_data.Class==1]
print(legit.shape)
print(fraud.shape)

(1983, 31)
(2, 31)

In [13]:
# statistical measures of the data
legit.Amount.describe()

count    1983.000000
mean       68.404892
std       241.572682
min         0.000000
25%         4.950000
50%        15.090000
75%        63.285000
max      7712.430000
Name: Amount, dtype: float64

In [14]:
fraud.Amount.describe()

count      2.000000
mean     264.500000
std      374.059487
min        0.000000
25%      132.250000
50%      264.500000
75%      396.750000
max      529.000000
Name: Amount, dtype: float64

In [15]:
# compare the values for both transactions
new_credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,760.974786,-0.281494,0.267200,0.848906,0.146804,-0.077904,0.051713,0.139533,-0.059771,0.014492,...,0.056618,-0.012217,-0.144666,-0.043548,0.013865,0.108318,0.049441,0.027220,-0.001966,68.404892
1.0,439.000000,-2.677884,-0.602658,-0.260694,3.143275,0.418809,-1.245684,-1.105907,0.661932,-1.520521,...,1.114625,0.589464,0.200214,0.455377,0.013198,0.162159,0.016239,0.004186,-0.053756,264.500000

Under Sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent transaction

number of fraudulent transactions -->108

In [16]:
legit_sample=legit.sample(n=108)

Concatenating two dataframes

In [17]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)
new_dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1482,1158,1.150559,0.217028,0.503593,1.066363,-0.461525,-0.745174,0.041322,-0.021768,-0.132318,...,-0.111975,-0.421642,0.057032,0.475331,0.380089,-0.580347,0.007138,0.018426,17.79,0.0
1812,1409,1.138785,-0.099399,0.464925,0.818293,-0.453077,-0.248068,-0.111777,0.035022,0.561227,...,-0.196775,-0.440876,0.028348,0.101214,0.348649,0.298017,-0.015217,0.012560,32.52,0.0
768,579,-1.296845,-0.511605,2.404726,-0.310762,-0.319551,-0.542842,-0.173310,0.260423,-1.202688,...,-0.071270,-0.161175,0.088496,0.285390,0.281069,-0.370130,0.043410,0.092318,80.00,0.0
371,271,1.196193,0.245161,0.631947,0.642941,-0.413133,-0.699728,0.019533,-0.112500,-0.047057,...,-0.203868,-0.533641,0.201929,0.406872,0.116137,0.102675,-0.009121,0.019700,0.89,0.0
1119,871,-0.789217,0.104689,1.013179,-1.743414,0.627381,-1.331799,0.416853,-0.164712,-1.642340,...,-0.241057,-1.089985,0.041864,-0.278966,0.042751,-0.769456,0.033546,0.120674,28.90,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1628,1261,1.008864,-0.688277,-0.481516,-1.332285,-0.530416,-1.186430,0.370423,-0.278458,1.087238,...,0.076271,0.003090,-0.210517,0.133448,0.552606,0.028854,-0.037211,0.027281,160.00,0.0
1964,1510,-2.886866,2.573611,-0.520661,-1.142153,-0.839929,-0.364637,-0.562656,1.547511,0.562283,...,-0.256608,-0.659522,0.029784,-0.553643,0.219229,0.365390,0.542426,0.338586,1.00,0.0
513,379,-1.896099,-1.829046,1.181222,3.897846,-1.686469,1.976371,-0.564107,-2.400465,-0.979202,...,-0.936346,-0.516626,-0.911682,0.025106,0.656699,0.200868,-0.088994,0.339814,881.13,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0

In [18]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1482,1158,1.150559,0.217028,0.503593,1.066363,-0.461525,-0.745174,0.041322,-0.021768,-0.132318,...,-0.111975,-0.421642,0.057032,0.475331,0.380089,-0.580347,0.007138,0.018426,17.79,0.0
1812,1409,1.138785,-0.099399,0.464925,0.818293,-0.453077,-0.248068,-0.111777,0.035022,0.561227,...,-0.196775,-0.440876,0.028348,0.101214,0.348649,0.298017,-0.015217,0.012560,32.52,0.0
768,579,-1.296845,-0.511605,2.404726,-0.310762,-0.319551,-0.542842,-0.173310,0.260423,-1.202688,...,-0.071270,-0.161175,0.088496,0.285390,0.281069,-0.370130,0.043410,0.092318,80.00,0.0
371,271,1.196193,0.245161,0.631947,0.642941,-0.413133,-0.699728,0.019533,-0.112500,-0.047057,...,-0.203868,-0.533641,0.201929,0.406872,0.116137,0.102675,-0.009121,0.019700,0.89,0.0
1119,871,-0.789217,0.104689,1.013179,-1.743414,0.627381,-1.331799,0.416853,-0.164712,-1.642340,...,-0.241057,-1.089985,0.041864,-0.278966,0.042751,-0.769456,0.033546,0.120674,28.90,0.0

In [19]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1628,1261,1.008864,-0.688277,-0.481516,-1.332285,-0.530416,-1.186430,0.370423,-0.278458,1.087238,...,0.076271,0.003090,-0.210517,0.133448,0.552606,0.028854,-0.037211,0.027281,160.00,0.0
1964,1510,-2.886866,2.573611,-0.520661,-1.142153,-0.839929,-0.364637,-0.562656,1.547511,0.562283,...,-0.256608,-0.659522,0.029784,-0.553643,0.219229,0.365390,0.542426,0.338586,1.00,0.0
513,379,-1.896099,-1.829046,1.181222,3.897846,-1.686469,1.976371,-0.564107,-2.400465,-0.979202,...,-0.936346,-0.516626,-0.911682,0.025106,0.656699,0.200868,-0.088994,0.339814,881.13,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0

In [20]:
new_dataset['Class'].value_counts()

0.0    108
1.0      2
Name: Class, dtype: int64

In [21]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,759.990741,-0.407791,0.170971,0.935629,0.176473,-0.151795,0.005306,0.029083,-0.006836,-0.021461,...,0.056743,-0.030536,-0.184722,-0.067077,0.019160,0.126673,0.121213,0.007780,-0.002164,78.129259
1.0,439.000000,-2.677884,-0.602658,-0.260694,3.143275,0.418809,-1.245684,-1.105907,0.661932,-1.520521,...,1.114625,0.589464,0.200214,0.455377,0.013198,0.162159,0.016239,0.004186,-0.053756,264.500000

Splitting the data into features & targets

In [22]:
x=new_dataset.drop(columns='Class',axis=1)
y=new_dataset['Class']

In [23]:
print(x)

      Time        V1        V2        V3        V4        V5        V6  \
1482  1158  1.150559  0.217028  0.503593  1.066363 -0.461525 -0.745174
1812  1409  1.138785 -0.099399  0.464925  0.818293 -0.453077 -0.248068
768    579 -1.296845 -0.511605  2.404726 -0.310762 -0.319551 -0.542842
371    271  1.196193  0.245161  0.631947  0.642941 -0.413133 -0.699728
1119   871 -0.789217  0.104689  1.013179 -1.743414  0.627381 -1.331799
...    ...       ...       ...       ...       ...       ...       ...
1628  1261  1.008864 -0.688277 -0.481516 -1.332285 -0.530416 -1.186430
1964  1510 -2.886866  2.573611 -0.520661 -1.142153 -0.839929 -0.364637
513    379 -1.896099 -1.829046  1.181222  3.897846 -1.686469  1.976371
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823

            V7        V8        V9  ...       V20       V21       V22  \
1482  0.041322 -0.021768 -0.132318  ... -0.167924 -0.111975 -0.421642
1812 -0.111777  0.035022  0.561227  ... -0.143277 -0.196775 -0.440876
768  -0.173310  0.260423 -1.202688  ... -0.349668 -0.071270 -0.161175
371   0.019533 -0.112500 -0.047057  ... -0.109478 -0.203868 -0.533641
1119  0.416853 -0.164712 -1.642340  ...  0.278140 -0.241057 -1.089985
...        ...       ...       ...  ...       ...       ...       ...
1628  0.370423 -0.278458  1.087238  ...  0.155957  0.076271  0.003090
1964 -0.562656  1.547511  0.562283  ...  0.451429 -0.256608 -0.659522
513  -0.564107 -2.400465 -0.979202  ...  2.538636 -0.936346 -0.516626
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477

           V23       V24       V25       V26       V27       V28  Amount
1482  0.057032  0.475331  0.380089 -0.580347  0.007138  0.018426   17.79
1812  0.028348  0.101214  0.348649  0.298017 -0.015217  0.012560   32.52
768   0.088496  0.285390  0.281069 -0.370130  0.043410  0.092318   80.00
371   0.201929  0.406872  0.116137  0.102675 -0.009121  0.019700    0.89
1119  0.041864 -0.278966  0.042751 -0.769456  0.033546  0.120674   28.90
...        ...       ...       ...       ...       ...       ...     ...
1628 -0.210517  0.133448  0.552606  0.028854 -0.037211  0.027281  160.00
1964  0.029784 -0.553643  0.219229  0.365390  0.542426  0.338586    1.00
513  -0.911682  0.025106  0.656699  0.200868 -0.088994  0.339814  881.13
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00

[110 rows x 30 columns]

In [24]:
print(y)

1482    0.0
1812    0.0
768     0.0
371     0.0
1119    0.0
       ...
1628    0.0
1964    0.0
513     0.0
541     1.0
623     1.0
Name: Class, Length: 110, dtype: float64

Split the data into Training data & Testing data

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [26]:
print(x.shape,x_train.shape,x_test.shape)

(110, 30) (88, 30) (22, 30)

Logistic Regression

In [27]:
from sklearn.preprocessing import StandardScaler
model=LogisticRegression(random_state=0,max_iter=1000)
#training the logistic regression model with training data
model.fit(x_train,y_train)
ypred=model.predict(x_train)

Model Evaluation

Accuracy Score

In [28]:
# accuracy on training data
x_train_prediction=model.predict(x_train)
training_data_accuracy=accuracy_score(x_train_prediction,y_train)

In [29]:
print("Accuracy on training data :",training_data_accuracy)

Accuracy on training data : 1.0

In [30]:
# accuracy on test data
x_test_prediction=model.predict(x_test)
test_data_accuracy=accuracy_score(x_test_prediction,y_test)

In [31]:
print("Accuracy score on test data:",test_data_accuracy)

Accuracy score on test data: 1.0